name: Cleanup

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  cleanup_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Cleanup workflow stale runs
        uses: Mattraks/delete-workflow-runs@bd2822c9d98065c9766fb1f4bbc32325c47de4fb # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "0"
          delete_run_by_conclusion_pattern: "cancelled,skipped"
      - name: Cleanup workflow success runs
        uses: Mattraks/delete-workflow-runs@bd2822c9d98065c9766fb1f4bbc32325c47de4fb # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "5"
          delete_run_by_conclusion_pattern: "success"
      - name: Cleanup workflow failure runs
        uses: Mattraks/delete-workflow-runs@bd2822c9d98065c9766fb1f4bbc32325c47de4fb # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "1"
          delete_run_by_conclusion_pattern: "action_required,failure"

      - name: Cleanup renovate caches
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO: ${{ github.repository }}
          PREFIXES: "renovate-repository-" # separate list items by space
          KEEP_COUNT: 3
        run: |
          echo "Fetching list of caches for $REPO with prefix $PREFIX..."
          cache_ids=$(gh cache list -R "$REPO" \
            --sort last_accessed_at \
            --order desc \
            --limit 100 \
            --json key,id,lastAccessedAt | \
            jq -r --arg p "$PREFIX" --argjson k "$KEEP_COUNT" \
            '.[] | select(.key | startswith($p)) | .id' | \
            tail -n +$(($KEEP_COUNT + 1)))
          if [ -z "$cache_ids" ]; then
            echo "No old caches to delete."
            exit 0
          fi
          echo "Found old caches to delete. Processing..."
          for id in $cache_ids; do
            echo "Deleting cache ID: $id"
            gh cache delete "$id" -R "$REPO" || echo "Failed to delete $id, skipping..."
            sleep 1
          done
          echo "Cache cleanup complete."

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1
