name: Renovate - Cached

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Cache Renovate Repository
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: /tmp/renovate/cache/renovate/repository
          key: renovate-repository-${{ github.run_id }}
          restore-keys: |
            renovate-repository-

      - name: Restore Permissions
        run: |
          if [ -d /tmp/renovate ]; then
            echo "fixing renovate perms"
            sudo chown -R 12021:0 /tmp/renovate/
          fi

      - name: Renovate Action
        uses: renovatebot/github-action@66387ab8c2464d575b933fa44e9e5a86b2822809 # v44.2.4
        env:
          LOG_LEVEL: "debug"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_TOPICS: "managed-by-renovate"
          RENOVATE_PLATFORM: "github"
          RENOVATE_PLATFORM_COMMIT: "true"
          RENOVATE_REPOSITORY_CACHE: "enabled"
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Keep last 4 Caches by Prefix
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO: ${{ github.repository }}
          PREFIXES: "renovate-repository-" # separate list items by space
        run: |
          for prefix in $PREFIXES; do
            echo "Processing cache prefix: $prefix"

            gh cache list -R "$REPO" \
              --sort last_accessed_at \
              --order desc \
              --limit 100 \
              --json key,id | \
            jq -r --arg p "$prefix" '.[] | select(.key | startswith($p)) | .id' | \
            tail -n +5 | \
            xargs -r -I {} gh cache delete {} -R "$REPO"
          done

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1
